{% set name = "dirty_cat" %}
{% set version = "0.4.2.post0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dirty_cat-{{ version }}.tar.gz
  sha256: 4d6895b3efbc45ac451cd08d49db6ff2bd6b7e96f92e251c21ee44bf7ebbb23e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - joblib
    - numpy >=1.17.3
    - pandas >=1.2.0
    - pyarrow
    - requests
    # due to "ImportError: cannot import name 'parse_version' from 'sklearn.utils'" error, need to pin sklearn below 1.5.1
    # see https://stackoverflow.com/questions/78519263/cannot-import-name-parse-version-from-sklearn-utils-users-aneeshnagarajan
    - scikit-learn >=0.23.0,<1.5.1
    - scipy >=1.4.0

test:
  imports:
    - dirty_cat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://dirty-cat.github.io/
  summary: Machine learning with dirty categories.
  dev_url: https://github.com/dirty-cat/dirty_cat
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
