{% set name = "dirty_cat" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dirty_cat-{{ version }}.tar.gz
  sha256: a9a4ca935701a2be88a0328e9be034176fd708fab4f1e29a034201780dd33707
  patches:
    - 0001-remove-benchmarks.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - joblib
    - numpy >=1.16
    - pandas >=1.1.5
    - python >=3.6
    - requests
    - scikit-learn >=0.21
    - scipy >=1.2

test:
  imports:
    - dirty_cat
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://dirty-cat.github.io/
  summary: Machine learning with dirty categories.
  dev_url: https://github.com/dirty-cat/dirty_cat
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
